import { contextBridge, ipcRenderer } from "electron";
//#region electron/preload.ts
contextBridge.exposeInMainWorld("electronAPI", {
	onRamGuardStatus: (callback) => ipcRenderer.on("ram-guard-status", (_event, value) => callback(value)),
	onProactiveMessage: (callback) => ipcRenderer.on("proactive-message", (_event, value) => callback(value)),
	onAiStateChange: (callback) => ipcRenderer.on("ai-state-change", (_event, value) => callback(value)),
	sendToOllama: (prompt) => ipcRenderer.invoke("send-to-ollama", prompt),
	addManualMemory: (memory) => ipcRenderer.send("add-manual-memory", memory),
	getMemoryStore: () => ipcRenderer.invoke("get-memory-store"),
	savePlaylistMemory: (name, uri) => ipcRenderer.invoke("save-playlist-memory", name, uri),
	clearSongCount: (uri) => ipcRenderer.invoke("clear-song-count", uri),
	saveSpotifyConfig: (id, secret) => ipcRenderer.send("save-spotify-config", id, secret),
	getSpotifyConfig: () => ipcRenderer.invoke("get-spotify-config"),
	authenticateSpotify: () => ipcRenderer.send("authenticate-spotify"),
	resizeWindow: (mode) => ipcRenderer.send("resize-window", mode),
	dragWindow: (dx, dy) => ipcRenderer.send("drag-window", dx, dy),
	endDrag: (vx, vy, wasDragged) => ipcRenderer.send("end-drag", vx, vy, wasDragged),
	setIgnoreMouseEvents: (ignore, options) => ipcRenderer.send("set-ignore-mouse-events", ignore, options),
	quitApp: () => ipcRenderer.send("quit-app"),
	openSettingsWindow: () => ipcRenderer.send("open-settings-window"),
	openCharacterEditor: () => ipcRenderer.send("open-character-editor"),
	getCharacterConfig: () => ipcRenderer.invoke("get-character-config"),
	saveCharacterConfig: (config) => ipcRenderer.invoke("save-character-config", config),
	onCharacterConfigUpdated: (callback) => ipcRenderer.on("character-config-updated", (_event, value) => callback(value)),
	getAvatarConfig: () => ipcRenderer.invoke("get-avatar-config"),
	selectAvatarImage: (state) => ipcRenderer.invoke("select-avatar-image", state),
	resetAvatarImage: (state) => ipcRenderer.invoke("reset-avatar-image", state),
	saveGeneratedAvatarSet: (images) => ipcRenderer.invoke("save-generated-avatar-set", images),
	onAvatarConfigUpdated: (callback) => ipcRenderer.on("avatar-config-updated", (_event, value) => callback(value)),
	sendMousePosition: (x, y) => ipcRenderer.send("mouse-position", x, y),
	navigateToPoint: (x, y) => ipcRenderer.send("navigate-to-point", x, y),
	onMicroAction: (callback) => ipcRenderer.on("micro-action", (_event, value) => callback(value)),
	onMousePosition: (callback) => ipcRenderer.on("mouse-position", (_event, x, y) => callback(x, y)),
	createBundle: (name, author, description) => ipcRenderer.invoke("create-bundle", name, author, description),
	installBundle: (bundleId) => ipcRenderer.invoke("install-bundle", bundleId),
	listBundles: () => ipcRenderer.invoke("list-bundles"),
	deleteBundle: (bundleId) => ipcRenderer.invoke("delete-bundle", bundleId),
	getUserName: () => ipcRenderer.invoke("get-user-name"),
	setUserName: (name) => ipcRenderer.invoke("set-user-name", name),
	onSetUserNamePrompt: (callback) => ipcRenderer.on("set-user-name-prompt", () => callback()),
	updateTrayIcon: (imagePath) => ipcRenderer.send("update-tray-icon", imagePath)
});
//#endregion
export {};
